
//----------------------------------------------------
// The following code was generated by CUP v0.11a czt01 beta
// Sun Jan 11 19:35:16 CST 2015
//----------------------------------------------------

package com.github.imay.json;

/** CUP generated class containing symbol constants. */
public class JsonParserSymbols {
  /* terminals */
  public static final int LBRACE = 4;
  public static final int COLON = 2;
  public static final int TRUE = 8;
  public static final int NULL = 10;
  public static final int STRING_LITERAL = 11;
  public static final int EOF = 0;
  public static final int FALSE = 9;
  public static final int RBRACKET = 7;
  public static final int NUMBER_LITERAL = 12;
  public static final int error = 1;
  public static final int COMMA = 3;
  public static final int LBRACKET = 6;
  public static final int RBRACE = 5;
}

